---  
- name: This will setup a NGINX Server
  hosts: all
  gather_facts: true
  become: true
  vars:
    nginx_use_ppa: true
    nginx_remove_default_vhost: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install dependencies.
      package: name=curl state=present
  roles:
    - geerlingguy.nginx

     
